### ISSUE TITLE
Favor hash literal syntax

### ISSUE THREAD

**Issue by acamino** [TwilioDevEd/server-notifications-sinatra#3]
When your hash keys are symbols use the syntax introduced in Ruby 1.9

```ruby
from: twilio_phone_number,
to: phone_number,
# ...
```

Please update [this](http://www.rubydoc.info/github/rspec/rspec-mocks/RSpec%2FMocks%2FExampleMethods%3Ahave_received) accordingly.

**Comment by nebtrx** [comment]
Done!
