### ISSUE TITLE
Use TWILIO_PHONE_NUMBER

### ISSUE THREAD

**Issue by acamino** [TwilioDevEd/server-notifications-sinatra#4]
https://github.com/TwilioDevEd/server-notifications-sinatra/blob/dad4a9b2e6c6389305ecf7ffc39cf5ffdb0f7d42/lib/notifier.rb#L21

Would you mind using `TWILIO_PHONE_NUMBER` instead of `TWILIO_NUMBER`?

**Comment by nebtrx** [comment]
Totally agreed with you, but...they're recently changing all env variables name from  TWILIO_PHONE_NUMBER to TWILIO_NUMBER.
