### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by acamino** [TwilioDevEd/server-notifications-sinatra#5]
Could you elaborate what is the idea behind printing [this](https://github.com/TwilioDevEd/server-notifications-sinatra/blob/dad4a9b2e6c6389305ecf7ffc39cf5ffdb0f7d42/lib/notifier.rb#L27-L28) to the console?

Anyway, **notitying** looks like a typo.

**Comment by nebtrx** [comment]
Done!
