### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by acamino** [TwilioDevEd/server-notifications-sinatra#7]
@nebtrx if we are not using `image_url` at all, you should consider remove it from the [method signature](https://github.com/TwilioDevEd/server-notifications-sinatra/blob/dad4a9b2e6c6389305ecf7ffc39cf5ffdb0f7d42/lib/notifier.rb#L20).

Please, bear in mind removing dead code will increase readability and maintainability.

EDIT.

Looks like your intention is to use `image_url`.

**Comment by nebtrx** [comment]
Done!. Apologies, I reuse the logic from the rail's implementation.
